### PR TITLE
Added explicit wait to the test

### PR DESCRIPTION
**Pull request by manuelq12**
Changes made to add explicit wait to the test using browser and ExpectedConditions

### CODE REVIEW

**Review by holgiosalos — COMMENTED** [review]
What do you think that is the best strategy for waits? and why?

**Comment by manuelq12** [comment]
What I understood in the description of each step, the benefits of the explicit wait is that is done in a more modular way than the implicit wait, what I could see in the test when I use explicit wait, it was a lot faster, i guess its because not every step we do in a test requires to wait or maybe not too much time, so I believe the best approach is Explicit wait, because if we use implicit wait we may make the test more slower.

**Comment by manuelq12** [comment]
And also because we only make the waiting in the cases that are needed

**Review by holgiosalos — APPROVED** [review]
Right! good job 👍

**Pull request merged**
